language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jam3' ]; then cd .. && eval "mv $currentfolder generator-jam3" && cd generator-jam3; fi
